/* 《被夺走的祖坟》英文版文字表  The Stolen Grave — English text table
 *
 * 〔用户裁定·2026-08-07·当面会话·"做英文版（不必动素材，对素材上的中文加标注翻译），
 *   做中英文切换按钮"〕
 *
 * 怎么用：页面里每一个会读的中文块都带一个编号（data-i="tNNN"），这个文件按同一编号
 * 存它的英文。切换到英文时，脚本按编号把内容换掉；表里没有的编号照旧显示中文。
 * 编号是静态写在 HTML 里的，不按顺序生成——增删一句话不会让后面的英文全部错位。
 *
 * 素材上的中文一律不动：画面里的文书是明代的文书，换成英文就不是它了。英文态改为在
 * 那一格下面补一行小字说明写的是什么，存在下面的 GLOSS 表里（data-gloss="gNNN"）。
 *
 * 来源与责任：主体取自花诗的英文正文 v5（`agents/花诗Vox-发言人/主线/公民网站/工作台/
 * 杨干院-正文-英文-v1.md`，2026-07-21 过馆主，标题定名 The Stolen Grave）与她的英文屏上
 * 文字 v1、尾声英文 v5。审校权在花诗（文案主责）。
 *
 * ── 每条行尾的出处标注（2026-08-07 补齐，184 条逐条判过；08-08 补t185—t189后共189条；
 *    08-09 补 t190「排年」注释后共 190 条，注释由 15 条增为 16 条）─
 *   无标注              这一条是花诗定稿里的原句，我没有改动。
 *   [据花诗英文改写]     取自她的英文稿，但为了适配页面分格做过拆分、压缩或接缝改写。
 *   [鹿诺初译]          我译的，她的英文稿里没有对应文字。
 *
 * 判据（可复核，不是凭印象分的）：
 *   1. 台词 30 条、注释 15 条一律记作我初译——**花诗的台词稿是中文的，她没有写过英文
 *      台词**；注释 15 条按 08-07 盘点本就归我初译。其中 6 条台词能在她的英文正文里命中
 *      八词以上，命中的全是史实名词串（"founded in 861 in Xiaonu township"、"land register
 *      of 1391 serial number bin 1999"），不是句子——那是我译台词时沿用了她已定的史实
 *      译名，句子本身仍是我写的，所以照记初译。
 *   2. 其余条目按与她三份英文正本的最长连续词组命中：八词以上记原文，五到七词记改写，
 *      四词及以下记初译。规范化时去掉标签、大小写与标点。
 *   3. 分档就低不就高——拿不准的一律往"我写的"那一边记。少标一条的代价是花诗把我的
 *      句子当成她自己的旧稿放过去，多标一条只是让她多看一眼。
 *
 * 为什么要补这套标注：08-07 第一次填表时只标了 9 条，其余 175 条无标注，等于宣称它们
 * 都出自花诗定稿。实际上台词、注释、年号、章题新定名、史料引文的英译都是我写的。花诗
 * 审校时若把我的初译当成自己 07-21 已过馆主的旧稿，就不会细看，错误会直接上线。
 */
window.EN = {

  /* ── 标题与章题 ───────────────────────────────────────── */
  t012: 'The Stolen Grave',   // [鹿诺初译]
  t013: 'A true lawsuit from Huizhou, in the Jiajing reign of the Ming',   // [鹿诺初译]
  t001: '§One&#12288;The Summons',   // [鹿诺初译]
  t002: '§Two&#12288;The Grave-Keepers',   // [鹿诺初译]
  t003: '§Three&#12288;The First Trial',   // [鹿诺初译]
  t004: '§Four&#12288;The Grave Is Levelled',   // [鹿诺初译] 08-08 改回英式拼写，全表唯一美式拼写（花诗审校必改4）
  t005: '§Five&#12288;Four Thousand Taels',   // [鹿诺初译]
  t006: '§Six&#12288;Two Years',                                          // [鹿诺初译] 新章名（旧幕六＋幕七合并）
  t007: '§Seven&#12288;The Tables Turn, and a File Goes Missing',   // [鹿诺初译] 08-08 补回"失窃"半章名，与t010两半题处理一致（花诗审校建议8，采纳）
  t008: '§Eight&#12288;The Night Session',                                // [鹿诺初译] 中文章名 08-05 由「夜审」定名，花诗旧幕名为 The Darkest Stretch
  t009: '§Nine&#12288;The Capital',   // [鹿诺初译]
  t010: '§Ten&#12288;The Judgment and the Missing Leaf',   // [据花诗英文改写]
  t011: 'Coda',   // [鹿诺初译]

  /* ── 黑场 ─────────────────────────────────────────────── */
  t145: '<p>How does a grave-keeping monk work up the nerve to evict the grave’s owner?<span class="bo-sub">For that, you have to go back to how the monastery began.</span></p>',
  t146: '<p>That was why Foxi dared to dump rubble on the tomb, and dared to order out its owner.</p>',
  t147: '<p>He understood it then: a lawsuit is not settled by how old a grave is, but by what evidence you hold.<br>And every piece that would stand up to checking was in the other side’s hands.</p>',   // [鹿诺初译]
  t148: '<p>Two years passed.</p>',   // [鹿诺初译]
  t149: '<p>This time, each side had learned the other’s methods.</p>',   // [鹿诺初译]
  t150: '<p>This war was nowhere near over.</p>',   // [据花诗英文改写]
  t152: '<p style="letter-spacing:.16em">Pressed and beaten, against the law</p>',   // [据花诗英文改写]
  t153: '<p>A complete circle, ending where it began.</p>',   // [据花诗英文改写]
  t151: '<p>From that day, a village grave case belonged to the throne.</p>',   // [鹿诺初译]
  t154: '<p>His enemy’s words, carved exactly as spoken.</p>',            // [鹿诺初译]
  t144: '<p>These wrongs, this pain, these loves and hatreds, the ancestors, the bloodline, the memory—<br>the state’s archives will not record them for us. So we record them ourselves.</p>',   // [鹿诺初译] 中文为馆主原话；08-08 blood→bloodline，避免读成流出的血（花诗审校必改7）

  /* ── 落点大字 ─────────────────────────────────────────── */
  t140: 'The caretakers were evicting the grave they had been hired to keep. Where under heaven was the sense in that?',
  t141: 'The one thing he never guarded against was the men he had himself installed to guard the grave.',
  t142: 'The brick vault of a tomb chamber came into the light. It had been there all along.',
  t143: 'He knew with perfect clarity that the first stop of this journey was a cell. He went anyway.',

  /* ── 四联年号（画面内小字） ───────────────────────────── */
  t181: 'Baoyou',   // [鹿诺初译] 08-08 公元年份改回年号，与同组另三格（Late Yuan/Hongwu/Jiajing）一致，年份已在t177/t094正文给过（花诗审校建议9，采纳）
  t178: 'Late Yuan',   // [鹿诺初译]
  t179: 'Hongwu',   // [鹿诺初译]
  t180: 'Jiajing',   // [鹿诺初译]

  /* ── 页底入口 ─────────────────────────────────────────── */
  t184: 'Sources &amp; Historical Note',   // [鹿诺初译]

  /* ── §一 传票 ───────────────────────────────────────── */
  t016: 'In the third month of 1528, in the village of Chengkan, Shexian County, Huizhou Prefecture, a man named Luo Xian paid a visit to Yanggan Monastery, just south of the village. Yanggan was a Buddhist monastery, and the ancestral grave of the Luo clan lay inside its grounds.',
  t092: 'The ancestral mound lay buried under a heap of broken brick and rubble. The monks had rebuilt their Buddha hall over the winter, and the workmen had dumped the debris on the nearest patch of open ground — the grave — and left it there the whole season. By Luo Xian’s generation, this grave was more than six hundred years old.',
  t102: 'Luo Xian and his clansmen cleared the rubble.',   // [据花诗英文改写] 她原句 'called over a few clansmen and cleared the rubble' 在这格里排两行、第一行伸到状纸底下被压住，为版面缩短
  t103: 'Then he waited for Foxi, the monk in charge of building works, to come out and explain himself.',
  t104: 'Foxi did not appear. He sent a novice out with a message.',
  t109: 'The message was not an apology. It was a request: would the Luo family kindly move their ancestral grave out of Yanggan Monastery.',
  t017: 'A few days later, what arrived instead was a summons from the county court. Foxi had sued him first. The charge on the complaint: forging an ancestral grave.',
  t093: 'Now Luo Xian would have to kneel in a courtroom and prove to the government that his family’s grave of six hundred years was real. And from the day the summons arrived, he was the accused.',

  /* ── §二 坟寺 ───────────────────────────────────────── */
  t094: 'In 1258, under the Southern Song, the head of the Luo clan was Luo Nai — one of Luo Xian’s own forebears — and he had a worry. The clan had scattered across the countryside, and every year at grave-sweeping time the crowd was thinner: the old could no longer manage the walk, and the young stood before the tomb not knowing whose it was. What worried him was the very grave that would lie buried under broken brick two hundred and seventy years later — the same grave.',
  t018: 'Luo Nai’s answer was to build a monastery beside the grave and endow it with farmland, so that monks would live there year-round and watch the tomb. Such a temple was called a grave temple: in plain terms, he was hiring his ancestors a staff of permanent, salaried tomb-keepers.',
  t056: 'There was a second layer of insurance. Luo Nai’s father-in-law was Cheng Yuanfeng, who had risen to Right Chancellor and Commissioner of Military Affairs. He personally wrote the inscription for the new monastery, and it was cut in stone and set up beside the temple.',
  t095: 'Anyone with designs on that tomb would first have to weigh the chancellor’s name carved into the stone.',
  t057: 'In that inscription Cheng Yuanfeng guarded against two kinds of men: the clan’s own wastrel descendants, and powerful outsiders looking for a crack to pry at.',   // [据花诗英文改写]
  t177: 'The Baoyou years: the grave stands at the centre of the compound. The monastery was built by the Luos to keep it.',   // [鹿诺初译]
  t174: 'Late Yuan: a Guanyin hall goes up, and a wall now runs across the front of the grave.',   // [鹿诺初译]
  t175: 'After the Hongwu reign: a bell tower, then a drum tower. Of the grave, only a mound of earth is left.',   // [据花诗英文改写]
  t176: 'Early Jiajing: the eaves almost reach the grave, and the path to it has grown over.',   // [鹿诺初译]
  t058: 'Over two hundred and seventy years the monastery prospered: the Guanyin hall, then the bell tower and the drum tower; the landholdings swelled; pilgrims came in ever greater numbers. At the grave it went the other way. The little Luo memorial shrine fell down and nobody repaired it, and fewer and fewer of the family came. By the early Jiajing years, this six-hundred-year-old ancestral grave was a mound of earth in the gap between the great monastery’s eaves.',   // [据花诗英文改写]
  t019: 'The official who oversaw every monk in Huizhou prefecture was called the <span class="term" data-annot="annot-dugang">Buddhist Registrar</span>. The Registrar of the day, Fachun, was Yanggan’s own man: from Xiuning, the next county over, he entered the monastery at eleven and took the abbot Fohai as his master. The office had always carried a price — whoever could pay, and could produce the joint guarantee of the local abbots, became on paper an “eminent monk.” Fohai had held it before him; when the master stepped down, the disciple paid and took it after him. And Foxi — the one who dumped the rubble, ordered out the grave’s owner, and filed suit first — was Fohai’s junior brother in religion, and so Fachun’s uncle in the dharma.',
  t155: '<b>Buddhist Registrar (dugang).</b> The Ming gave the clergy an administration of its own: a Central Buddhist Registry in the capital, a prefectural office, a sub-prefectural office, a county office. Each prefecture had one Registrar, ranked 9b — the lowest rung of the imperial ladder — and unsalaried. He administered the temples and monks of his prefecture: their registration, their ordination certificates (the government-issued licence without which taking orders was illegal), and disputes between clergy and laity, which usually passed through his hands first. By statute the Registrar was to be chosen from monks of good discipline and learning. In Jiajing-era Huizhou the practice was to pay, and to assemble the joint guarantee of the local abbots. That is how Fachun came by the office.',   // [鹿诺初译]

  /* ── §三 第一场公堂 ─────────────────────────────────── */
  t096: 'Foxi had sued first. It looks like a head start of a few days; it was worth far more than that.',
  t087: '<p>First: under Ming rules, ordinary people could not go straight to court. A dispute had to go before the <span class="term" data-annot="annot-lilao">community elders</span> for mediation, and only if mediation failed could you file suit. Temples were exempt. So for Luo Xian to sue Foxi, he had to wait in line; for Foxi to sue Luo Xian, the case went straight to trial.</p> <p>Second: whoever files first decides what the case is about. The complaint said “the Luos forged a grave,” so forgery — and only forgery — was what the court would try. From his first word, Luo Xian would be a man defending himself.</p> <p>Third: by imperial regulation, in any lawsuit where a temple stood as plaintiff, the Buddhist Registrar was entitled to attend court.</p>',
  t156: '<b>Community elders (lilao).</b> The Ming organised the countryside into <i>li</i> of one hundred and ten households. Each <i>li</i> chose several men of age and standing as its elders. One of the duties the throne assigned them was mediation: disputes over land, marriage or affray went first to the elders, and only if they failed to settle it could a complaint be taken to the yamen. Go over the elders’ heads and your complaint could be thrown out. For an ordinary person, then, the elders were the first door of any lawsuit, and there was no way round it.',   // [鹿诺初译]
  t059: 'On the opening day, Luo Xian walked into the county yamen, looked up—',
  t020: 'He had four things on his side: the grave, standing there since the last years of the Tang; the stele of Chancellor Cheng Yuanfeng; the prefectural and county gazetteers, with the Luo grave recorded in black and white; and the clan genealogy, which the whole neighbourhood could vouch for. He did not see how this case could be lost.',
  t110: '<span class="who">FACHUN</span>The grave? Go and look at it: a cramped little mound, eight courses of brick, not even lime in the joints.<br>What family’s six-hundred-year-old ancestral tomb looks like that? Plainly something thrown together, and recently.',   // [鹿诺初译]
  t111: '<span class="who">LUO XIAN</span>Nonsense! That grave has been there since the end of the Tang!<br>It is written in our genealogy — send for the neighbours and ask them, any of them!',   // [鹿诺初译]
  t112: '<span class="who">FACHUN</span>The genealogy the Luos compiled themselves. As for the neighbours, this court will summon them in due course.<br>Now the gazetteers. One vague line about a Luo grave, and the location vague — what makes that line this grave?',   // [鹿诺初译]
  t113: '<span class="who">LUO XIAN</span>The stele! Chancellor Cheng Yuanfeng wrote it with his own hand, and there it stands!',   // [鹿诺初译]
  t114: '<span class="who">FACHUN</span>I was coming to the stele. The inscription says plainly: that monastery was moved here from Ningtai township.<br>This monastery’s own history: founded in 861 in Xiaonü township, moved three times before settling at Yanggan — no connection to Ningtai whatsoever.<br>The temple in that inscription is simply not this temple.<br><br>Which is to say: for several hundred years, your family has been bowing to the wrong grave.',   // [鹿诺初译]
  t115: '<span class="who">LUO XIAN</span>I—',   // [鹿诺初译]
  t116: '<span class="who">FACHUN</span>One thing more.<br>The <span class="term" data-annot="annot-baobu">land register</span> of 1391, serial number Bin 1999.<br>For the entire estate of Yanggan Monastery, the entry runs to four characters—',   // [鹿诺初译]
  t157: '<b>The land register (liushui baobu).</b> In 1391 the founding emperor ordered a survey of every acre in the realm; temple property was entered item by item, numbered and filed. This was the empire’s real-estate ledger. Whatever the register said, the government took to be the ownership. Word of mouth, a family genealogy, an inscription on stone — none of them outweighed one line of it.',   // [鹿诺初译]
  t117: '<span class="who">FACHUN</span>The whole property, administered by the monastery. Nothing to do with any Luo family.',   // [鹿诺初译]
  t118: '<span class="who">FACHUN</span>One further point, which I ask the court to enter in the record.<br>This monastery has been building since the founding reign; the dharma hall stands less than four paces from the front hall — if your ancestral grave really lay in between, we should have built over it long ago.<br>And in a hundred-odd years, your family never said a word?',   // [鹿诺初译]
  t119: '<span class="who">LUO XIAN</span>We… when I was a boy, I did come to sweep the grave…',   // [鹿诺初译]
  t170: '“From the Hongwu to the Hongzhi reign we have repeatedly built and rebuilt the dharma hall, which stands less than four paces from the front hall. Had there truly been a grave between them, it must long since have been built over. Why has the family never spoken of it?”',
  t097: 'Standing below the bench, Luo Xian was argued into silence.',   // [鹿诺初译]

  /* ── §四 铲坟 ───────────────────────────────────────── */
  t014: 'The witnesses were called in one after another, and one after another they hedged and mumbled — the monastery had bought them all in advance. Follow the strings on these paper men, and the far end of every one was in the Registrar Fachun’s hand.',   // [据花诗英文改写]
  t021: 'Worse was to come. Two Luo kinsmen who had long since split off from the household, Luo Chengshan and Luo Hushe, stood up in open court and denounced Luo Xian to his face. Standing there, he saw one thing only: of all the witnesses in that hall, not one would speak for him.',
  t022: 'Then there was the presiding magistrate, Gao Qi. The local gazetteer preserves an assessment of him: he flogged men for the smallest offence, and when they protested he flogged them harder in his anger, and had beaten men to death; and he was greedy, and never had enough.',
  t023: 'An isolated old countryman, standing before a judge who took money and beat men to death — what was he supposed to do? Luo Xian was afraid. He confessed.',
  t015: 'The judgment: the so-called Luo grave was a “loose heap” — not a tomb, a pile of dirt. The county then sent men to level it. On the day the bailiffs put their spades in, Luo Qiuyin had been lying there for more than six hundred years.',

  /* ── §五 四千两 ─────────────────────────────────────── */
  t098: 'After the county’s judgment came down, Luo Xian went back to Chengkan and called the head of every branch of the clan into the ancestral hall.',   // [鹿诺初译]
  t120: '<span class="who">LUO XIAN</span>Heads of the branches, I will put it plainly. This lawsuit is not about avenging Luo Xian.<br><br>If the government has ruled the grave false, then the origin of the Luo clan is false.<br>Our genealogy begins at that grave. What makes several hundred people one family? The ancestor lying in it — nothing else.<br><br>Today the monks who were hired to keep the grave dare to seize it, and the government helps them. Tomorrow someone comes for the fields, the houses, this hall.<br>Swallow this, and from now on in Shexian the Luos are a family anyone may help themselves to.',   // [鹿诺初译]
  t121: '<span class="who">A BRANCH HEAD</span>Our branch puts in seven hundred and twenty taels.',   // [鹿诺初译]
  t122: '<span class="who">OTHERS</span>Six hundred and fifty. Three hundred. One hundred.',   // [鹿诺初译]
  t123: '<span class="who">THE LAST, AFTER A PAUSE</span>…A dozen taels or so. We will put in too.',   // [鹿诺初译]
  t124: '<span class="who">LUO XIAN</span>And eight men, to work on nothing but this case with me.',   // [鹿诺初译]
  t088: '<p>The clan raised some four thousand taels of silver — enough to buy eight thousand piculs of rice, the savings of several generations. Lawsuits cost that much because a Ming lawsuit could be appealed: above the county was the prefecture, above the prefecture the provincial censor, and at the top the capital, and appealing up each rung was lawful. But every rung cost money — money for the writing of the complaint, money for the clerks, money for the runners; and every time a case changed yamen, every deposition was taken again and every file requisitioned again, which meant fighting the whole case from the beginning. The four thousand taels were for that.</p>',
  t024: 'Shexian was out — he had just lost there. The prefectural seat of Huizhou was in the same city, where Fachun’s silver and Fachun’s connections worked just as well. Luo Xian went to a third place: the <span class="term" data-annot="annot-xunan">Regional Inspector’s office</span>.',
  t158: '<b>Regional Inspector (xun’an yushi).</b> An investigating censor of the Censorate, sent out from the capital to tour a province. He ranked only 7a, yet he travelled as the throne’s own eye: whether officials were fit for their posts, whether there were miscarriages of justice, all fell to him — “touring on the Son of Heaven’s behalf.” He was not a local man, and when his term ended he left, so local face counted for little with him and silver was hard to get into his hands. A Grand Coordinator, by contrast, was the highest authority in a province, far senior to the Inspector and responsible for a great deal — and because his charge was so broad, he did not usually try private disputes himself. He wrote a line on the complaint and sent it back down to the local yamen.',   // [鹿诺初译]
  t025: 'The complaint was carefully built. It did not begin with the grave. It began by charging Yanggan Monastery with harbouring vagrants and with monks who broke their vows, so that whoever read it would first form the picture of a lawless clergy; only then did it come to the grave and its history; and at the end it charged Magistrate Gao Qi himself — taking bribes, and abusing the instruments of punishment. That last charge was the point: under the <span class="term" data-annot="annot-huidian">Collected Statutes of the Ming</span>, if a complaint alleged that an official had extorted confessions or manufactured a miscarriage of justice, the Regional Inspector was forbidden to delegate it and had to hear it himself. Luo Xian had left himself a second move.',
  t159: '<b>The Collected Statutes of the Ming (Da Ming huidian).</b> An officially compiled digest of administrative law that set out, office by office, the duties and procedures of every government body — the working handbook of Ming officialdom. It laid down that where a complaint alleged an official had “perverted a criminal case” (extorted confessions, manufactured a wrongful conviction), the Regional Inspector could not delegate it to anyone else but had to try it in person. That is why Luo Xian named Gao Qi at the end of his complaint.',   // [鹿诺初译]
  t026: 'The Inspector transferred the case to the neighbouring prefecture of Ningguo. There the <span class="term" data-annot="annot-tuiguan">judicial commissioner</span> Guo Fengyi did the whole job: he requisitioned the original Shexian file, collected gazetteers old and new, the temple stele and the family genealogy, and questioned the elders and neighbours all over again.',   // [鹿诺初译]
  t160: '<b>Judicial commissioner (tuiguan).</b> The officer in charge of criminal matters in a Ming prefecture, ranked 7a, whose work was the hearing of cases and the review of case files. A prefect’s duties were many and various, so the actual questioning and inspection usually passed through the commissioner’s hands; the quality of justice in a prefecture often came down to who was sitting in this one chair.',   // [鹿诺初译]
  t027: 'At last he sent men over the Huangshan range to Yanggan Monastery, to dig.',   // [据花诗英文改写]
  t060: 'For the first time in six hundred years, this grave had to have bailiffs open the earth above it in order to prove to the government that it existed.',   // [据花诗英文改写]

  /* ── §六 两年 ───────────────────────────────────────── */
  t099: 'On the day the grave was restored, the government sent an officer to watch, and the entire community of Yanggan monks, together with the elders and neighbours from round about, were summoned to look on. In front of all of them, Foxi rebuilt with his own hands, one basket of earth at a time, the mound he had ordered levelled. When it was done he said nothing and walked away. The Luo family had waited two years for that day.',   // [鹿诺初译]
  t089: '<p>The Ningguo judgment ran like this. The grave was genuine and the mound was to be rebuilt; since Foxi had ordered it levelled, Foxi personally was to rebuild it. The Luos’ right to sweep and sacrifice at the tomb each spring was restored. A room on the east side of the Guanyin hall was set aside for a Luo shrine. And Foxi, found to have had illicit relations with a woman named Manzhen, had his <span class="term" data-annot="annot-dudie">ordination certificate</span> revoked and was ordered back into lay life.</p>',   // [据花诗英文改写]
  t161: '<b>Ordination certificate (dudie).</b> The state-issued document that made a man a monk in the eyes of the government — his licence, in effect. With it he was recognised clergy and exempt from tax and labour service; without it, taking orders was illegal and punishable. It was printed by the Ministry of Rites and carried the holder’s religious name, native place and monastery. To have it revoked was to be struck from the clergy and sent home a commoner: for a monk, the heaviest penalty there was, short of the criminal law.',   // [鹿诺初译]
  t028: 'Then the government had both parties draw up a <span class="term" data-annot="annot-ganjie">bond of settlement</span> and sign and seal it.',   // [鹿诺初译]
  t162: '<b>Bond of settlement (ganjie).</b> A closing formality of Ming litigation: the two parties wrote out, before the court, a guarantee bearing their signatures and marks, undertaking to abide by the judgment and never to sue over the matter again. Once the bonds were made, the case counted as closed on the government’s books. This sheet of paper would later vanish from the file — and it was exactly what Fachun needed gone in order to reopen the case.',   // [鹿诺初译]
  t090: '<p>The grave was back and the case was won, and neither side was satisfied. The judgment separated the right of sacrifice from the ownership of temple property: the Luos might come each year and sacrifice at the tomb; the estate remained the monastery’s; and it was written in that the Luos might not use the grave to claim any part of that estate. What the monks had wanted was a temple with clear title and no grave in it — and now the mound was back, and there was a Luo shrine inside their walls besides. What the Luos held was that the whole of Yanggan Monastery had been built with their money in the first place, and all they had recovered was one grave and one room.</p>',   // [据花诗英文改写]
  t029: 'On the fifteenth of the seventh month of 1530, the Ghost Festival, Yanggan Monastery held a great assembly, open to monks and laity, men and women alike. The young people of Chengkan went in a crowd to watch, and among them went Zheng Laibao, the Luo family’s adopted son, with his wife and several women of the clan.',
  t030: 'That night a man was killed in the monastery: in a brawl, Zheng Laibao was beaten to death. A monk named Zhideng carried the body out of the compound and burned it. The man was dead and the corpse was ash; how exactly he had died could never afterwards be established.',
  t031: 'Before the Luos had finished the funeral, Yanggan’s complaint was already lodged at the yamen — and it told a different story. The Luos, coveting temple property, had gathered men and forced their way into the assembly to make trouble, and had beaten to death two of the monastery’s monks, Nengni and Foyuan. On one and the same night, the man who died was the Luos’ adopted son; the complaint that was filed said the dead were monks and the attackers were Luos. Two years earlier Foxi had got in ahead of Luo Xian with a charge of forging a grave. This time Fachun got in ahead of the Luos with a charge of murder. Whoever files first decides what the case is about.',
  t091: '<p>Why did there have to be a killing at all? Because the two sides had signed bonds of settlement promising not to sue again, so there were no grounds on which to reopen the grave case directly — whereas a homicide was a capital matter, and one new murder case would drag the old one back into court with it. Zheng Laibao had died in circumstances nobody could account for. In Fachun’s hands, that became an opening.</p> <p>Where to file, Fachun had also learned from Luo Xian. He filed with the Grand Coordinator’s office. The Grand Coordinator had a standing practice: he did not try private disputes himself; he wrote a line on the complaint and sent it back down to the local yamen. One transfer, and the case was back in Huizhou prefecture — where Fachun was Buddhist Registrar. The same machinery that Luo Xian had used two years before to send the case out of Huizhou, Fachun now used to bring it home.</p>',   // [据花诗英文改写]

  /* ── §七 翻盘与失窃 ─────────────────────────────────── */
  t066: '<p>This time Luo Xian did not wait for the hearing. He went first to the Regional Inspector’s office and reported the killing of Zheng Laibao there too, in the same words — one event, filed with two yamen.</p> <p>The value of that step lay in the different rules the two offices followed when they passed a case on. The Grand Coordinator took a private complaint, wrote a line on it, sent it back down to the locality, and was finished with it; he did not look at it again. The Inspector was another matter: a case he referred out was registered and numbered, given a deadline for judgment, and if the deadline passed the officers handling it were called to account; when it was decided, the decision came back to him for approval. Routed through the Inspector, a case acquired someone watching it from above.</p> <p>So the prefect of Huizhou did not dare hand this one to a judicial commissioner below him. He assigned it to the prefecture’s second man, <span class="term" data-annot="annot-tongzhi">Vice Prefect</span> Li Bang, to try in person. Fachun could afford to buy a commissioner; Li Bang was the prefect’s own deputy, and with the case registered at the Inspector’s office, showing favour would cost him his post.</p> <p>Then there were the witnesses. The Luos had been burned once by bought testimony, and this time they had men keep an eye on the <span class="term" data-annot="annot-painian">annual-service households</span>. One of them, Hu Tongjin, was in debt; he took Foxi’s silver and went straight off to pay what he owed, and a Luo man saw him do it. They called on him and he told them the whole thing.</p>',   // [据花诗英文改写]
  t163: '<b>Vice Prefect (tongzhi).</b> A Ming prefecture was headed by a prefect; the vice prefect, ranked 5a, was his deputy, one or two to a prefecture, with charge of grain administration, public order or judicial business. The prefect held the whole, and important cases were commonly given to the vice prefect to try.',   // [鹿诺初译]
  t190: '<b>Annual-service households (painian).</b> The Ming organised the countryside into <i>li</i> of one hundred and ten households. Within a <i>li</i>, the ten households with the most land and adult men held the office of ward head in turn, one household a year over a ten-year cycle. The year a household was on duty was called its “current year”; the years it was not on duty were its “ranked years” — <i>painian</i> — so that “the annual-service men of this ward” meant those of the ten not serving that year. Being off duty did not put a household outside the business of the ward: these were still the men answerable for it, and when the authorities looked into a local matter they were commonly the first summoned to give evidence. That is why both sides in this suit paid so heavily for them.',   // [鹿诺初译] 08-09 新增第16条注释；花诗08-08在审校第5项提过中英文都没有一处解释排年，独立读者审查同日四人独立命中同一缺口（上班族从0159卡到全篇末）
  t125: '<span class="who">FOXI</span>Gentlemen of the annual service, we are all neighbours here. Let me drink to you first.',   // [鹿诺初译]
  t126: '<span class="who">FOXI</span>The complaint has been endorsed from above.<br>On the day of the hearing — gentlemen will remember what is to be said.',   // [鹿诺初译]
  t139: '<span class="who">FOXI</span>I would not trouble you for nothing.',   // [鹿诺初译]
  t182: 'Three taels one mace of gold and thirty taels of silver, divided at the table.',   // [据花诗英文改写]
  t127: '<span class="who">FACHUN</span>Let the annual-service men of this ward be called, to give—',   // [鹿诺初译]
  t128: '<span class="who">LUO XIAN</span>A moment. There is something this man would lay before your honour first.<br>On the twenty-fifth of the eleventh month last year, Yanggan Monastery laid on a banquet, and every guest was an annual-service man of this ward.<br>At that table three taels one mace of gold and thirty taels of silver were shared out, so that these gentlemen would come into court and remember what to say.<br>As to who took the money — this man will give your honour the names, one by one.',   // [鹿诺初译]
  t129: '<span class="who">HU TONGJIN, KNEELING</span>Three… three mace one candareen of gold, three taels of silver. I have brought it all with me.<br>I confess. I confess everything.',   // [鹿诺初译]
  t032: 'Three years earlier in that same courtroom, Fachun had argued Luo Xian into silence, and he had ended by pressing his thumbprint to a confession. This time he read out, item by item, in front of the whole court, the amount of every bribe, the date of it, and the name of the man who took it.',   // [据花诗英文改写]
  t033: 'Buying witnesses has one flaw the buyer cannot close: once the money is in the witness’s hands, it becomes a thing that can be produced in court. These annual-service men were ordinary villagers who could not stand up to examination on the spot; handing over the silver and explaining where it came from was a far better bargain than taking the fall for a monk.',   // [鹿诺初译]
  t034: 'The two men who had witnessed the killing that night were sent for by the court. The report came back: both had died of illness and were already buried. With the witnesses gone, the homicide could not be pursued, and the grounds for holding Fachun in gaol could not be made out. He could not be held; he had to be let go.',
  t035: 'Li Bang ordered up the old file on the grave case. The bailiff sent to fetch it was bought by Foxi and stayed home pleading sickness, while an unordained temple servant went in his name and drew the file out without difficulty — and took it first to Foxi to read. Foxi removed the Ningguo volume and sent the rest on to the Huizhou yamen. The government’s own case file, travelling from Ningguo to Huizhou, passed through Foxi’s hands on the way: two volumes in, one volume out.',   // [据花诗英文改写]
  t036: 'When the file came back, Luo Xian went through it page by page. One sheet was still missing: the bond of settlement the two families had signed and sealed. They had been willing to return a stolen case file, and had kept back only the guarantee never to sue again — which meant they intended to sue again.',   // [据花诗英文改写]

  /* ── §八 夜审 ───────────────────────────────────────── */
  t100: 'Eighty strokes, laid on Fachun.',   // [鹿诺初译]
  t067: '<p>Li Bang had several interlocking cases on his hands. He asked two magistrates from neighbouring counties to sit with him and try them together, with every official of his own county standing aside. The two magistrates heard the case and gave judgment: the grave was genuine, the Ningguo ruling stood, and boundary stones were to be set; Luo Xian and Fachun were each to receive eighty strokes; Foxi, for bribery and for tampering with the file, was ordered back into lay life. As to the deaths — Nengni, Foyuan, Zheng Laibao, and the two witnesses who had died in gaol: five lives, all of them entered in the judgment as death by illness, and pursued no further.</p>',
  t061: 'Fachun had lost this round. But while the strokes fell his mind kept working, and out of that judgment he read what the government wanted: the two magistrates had not failed to uncover those five deaths — they had chosen not to look. The messier a case grows, the more the government wants it over; and the more it wants it over, the vaguer it is willing to be.',
  t037: 'To each of the six annual-service men who had just been beaten, Fachun sent fifty taels of silver. Some time later, each of the six carried his fifty taels to the yamen and “surrendered” it, denouncing Luo Xian: this is the bribe money he gave us to testify for him. The silver was real, the surrender was real, and the six depositions corroborated one another. The only false thing in the whole arrangement was where the money had actually come from — and where money comes from is precisely what nobody can prove. Luo Xian had almost nothing to answer with.',
  t038: 'A newly arrived Regional Inspector, who knew nothing of the past few years, sent the homicide back for retrial to Chizhou, the prefecture to the north-west — and the six “surrendered” exhibits travelled with the file. Of the eight years behind them, Chizhou knew nothing at all.',   // [据花诗英文改写]
  t039: 'The hearing was set for the evening. A prefectural city kept a <span class="term" data-annot="annot-xiaojin">night curfew</span>: at the drum the streets emptied, and outside the court there was not one bystander.',   // [鹿诺初译]
  t164: '<b>Night curfew (xiaojin).</b> In Ming prefectural and county towns a drum was beaten at nightfall and no one was permitted on the streets thereafter. To set a hearing after curfew was to guarantee that no member of the public could be outside the court; whatever happened inside, no one out there would see it.',   // [鹿诺初译]
  t130: '<span class="who">LUO XIAN</span>This man has a defence to—',   // [鹿诺初译]
  t131: '<span class="who">BAILIFF</span>Silence in court!',   // [鹿诺初译]
  t132: '<span class="who">LUO XIAN</span>Let the neighbours be summoned—',   // [鹿诺初译]
  t133: '<span class="who">LUO XIAN</span>Let the Ningguo file be sent for—',   // [鹿诺初译]
  t134: '<span class="who">THE COMMISSIONER, NOT LOOKING AT HIM, AS IF DISPOSING OF A ROUTINE MATTER</span>It is getting late.<br>Put him in the press.',   // [鹿诺初译]
  t040: 'The ankle press: an instrument that crushes the shinbones. That night it was used on a countryman of past sixty.',   // [鹿诺初译]
  t041: 'Writing of that night afterwards, in a complaint, he used four characters—',   // [鹿诺初译]
  t171: '“Unexpectedly the treacherous monks conspired with Tang Wenkui, a long-practised fixer of yamen business, and bribed the officers. On the fifteenth day of the ninth month they contrived to reach the place towards evening; the neighbours were not examined, the original file was not consulted, no statement of defence was taken — and I was pressed and beaten, against the law.”',   // [据花诗英文改写]
  t183: 'The price was one tael of silver per alteration.',   // [据花诗英文改写]
  t042: 'The file was tampered with as well. The presiding commissioner bought the copying clerk, and through years of accumulated depositions, wherever a neighbour had said “there is a grave,” it was altered, one instance at a time, to “there is no grave.” On paper the witnesses’ names were unchanged; what they had said was now the exact opposite.',
  t106: '<p>One night more than three hundred men came into Yanggan Monastery with torches and opened the grave from the top. By torchlight the brick chamber came into view, and with it an epitaph stone — several hundred people saw it. What they did not reach was a coffin or any bones. With brick and an epitaph, you can call it a grave; without coffin or bones, you can call it a forgery. In any case, early the next morning the same men came back and scraped the whole site clean.</p> <p>The grave was gone. The case was not. Luo Xian went on suing.</p>',
  t062: 'The witnesses’ statements had been rewritten, the words in the file had been rewritten, the grave had been dug open and scraped flat. By this point in the lawsuit, everything capable of proving that this grave existed had been got at.',   // [鹿诺初译]

  /* ── §八 绕圈三格（08-07 补：这三条原先漏了编号，英文态下读者会撞见中文） ─ */
  t185: 'Luo Xian went for help to Ningguo — the court that had once dug the truth out of the ground. Ningguo said: the case belongs to Chizhou now; we cannot intervene.',
  t186: 'He turned to Huizhou. Huizhou said: the case is in Chizhou — and pointed him back again.',
  t187: 'So back to Chizhou he went. Chizhou was the court that had put him in the press against the law.',   // [鹿诺初译] 08-08 避免had had连读绊口，press呼应t134/t040已立的说法（花诗审校建议11，采纳）

  /* ── §九 京城 ───────────────────────────────────────── */
  t081: '<p>The Chizhou judgment had come out of the hands of a judge who had taken money. The judgment itself could not be overturned — so he would sue the man who had made it. The rule in the Collected Statutes: a case against an official goes to that official’s superior. Above the Chizhou prefecture there was no higher yamen in this region, and so the case came back to the Regional Inspector. This time he had to hear it himself. There was no longer anywhere to pass it down to.</p>',
  t043: 'The Inspector Zhan Kuan took the case. To the depositions and files that had been altered and altered again he paid not the slightest attention — after that many hands, true and false could no longer be told apart. He changed the whole basis on which the case would be tried, and brought out something else entirely: the ritual law of the dynasty. First the Luos: a commoner family might not maintain a shrine for the exclusive sacrifice to an ancestor; this grave was in breach of the code, and was to be levelled. Then the monastery: its newly made images were in the nature of an <span class="term" data-annot="annot-yinci">unsanctioned shrine</span>, which imperial edict forbade; the Buddha hall was to be demolished.',
  t165: '<b>Unsanctioned shrine (yinci).</b> A shrine or cult outside the register of state-approved sacrifices and without official licence. <i>Yin</i> here means excessive, irregular — nothing more. Ming law expressly forbade the founding of such shrines by private persons, and those discovered were to be pulled down.',   // [鹿诺初译]
  t044: 'In the twelfth month of 1533, government men entered Yanggan Monastery. The grave was levelled a second time and the Buddha hall was demolished; the central hall of the monastery was converted into a shrine for the sacrifice to Cheng Yuanfeng, who had written the stele — on the ground that his name was on it. The old chancellor had written that stone three hundred years earlier to protect his son-in-law’s family grave. Three hundred years later he was set up on the altar himself and given incense, while the grave he had meant to protect, a few paces from the altar, was scraped level with the ground.',
  t082: '<p>Eight years. Witnesses, judges, bailiffs, clerks — both sides had bought all of them, and everything could be arranged with money. Here, for the first time, the case ran into something money could not move: the ritual code of the dynasty. Zhan Kuan did not ask who was in the right, and he did not ask who was paying more. Going by the ritual canon, he stripped each family of the thing it valued most: the Luos lost the grave, the monastery lost its Buddha hall. At that point Fachun stopped. Luo Xian did not.</p>',
  t045: 'He finally established it: Nengni and Foyuan, the two monks, had died before this lawsuit ever began. Yanggan Monastery had been keeping dead monks on its clerical register, so that when the government came to count heads and assign service obligations, it could make up the numbers with the names of the dead. Which is to say: the two monks “beaten to death by the Luos” had not been alive when the offence took place.',
  t105: 'Seven complaints in eight years.',   // [鹿诺初译] 原译两行、第一行被上层状纸压住，缩到一行
  t083: '<p>But with this new evidence in hand, Luo Xian found there was nowhere left to take it. Every yamen in the region, large and small, he had already been to in eight years. Above them there was only the capital. Going to the capital to sue was called <span class="term" data-annot="annot-jingsu">appeal to the capital</span> — and the act itself was a crime: right or wrong, the man who brought the complaint was punished first and gaoled first. Luo Xian was old, and the law also forbade the old to make the journey. At this point his nephew Luo Xing stepped forward.</p>',   // [据花诗英文改写]
  t166: '<b>Appeal to the capital (jingsu).</b> The Ming forbade skipping levels of appeal. To carry a complaint past the county, the prefecture and the province directly to the capital was itself an offence, called <i>yuesu</i>, appeal out of order: right or wrong, you were first sentenced for it — flogged, imprisoned — and only then did the hearing of your case begin. So the first stop for anyone who went to the capital to sue was prison. The law further barred the elderly from making the journey; Luo Xian could not go, and it had to be Luo Xing.',   // [鹿诺初译]
  t046: 'Early in 1535 Luo Xing reached the capital with the complaint and submitted it to the <span class="term" data-annot="annot-tongzhengsi">Office of Transmission</span>. The office examined the complaint, accepted it, and then had him put in prison. This was not a mistake. Ming law held that to pass over the county, the prefecture and the province and bring a suit directly in the capital was in itself an offence; the plaintiff was gaoled on that charge first, and the hearing began afterwards. Every step in his imprisonment was in accordance with the law.',   // [据花诗英文改写]
  t167: '<b>Office of Transmission (tongzhengsi).</b> The central office in the capital that received memorials and petitions from the whole empire. Documents sent up from every province passed through it to be checked and registered before being distributed to the emperor and to the various ministries. Its head, the Transmission Commissioner, had the standing to report important documents aloud at the morning audience.',   // [鹿诺初译]
  t047: 'On the twelfth day of the fourth month, at morning court before the Fengtian Gate, the Transmission Commissioner Chen Jing stepped from the ranks and reported a case about an ancestral grave in Shexian County, Huizhou Prefecture, in open court before the Jiajing Emperor.',   // [据花诗英文改写] 08-08 改回花诗英文正本第294行原句（花诗审校必改1）
  t048: 'As it happened, this emperor was the son of a princely house. Since his accession he had been fighting the entire court for more than a decade to obtain an imperial title for his own natural father, and the quarrel had not yet subsided. A lineage that had gone to law for eight years over the standing of its founding ancestor, gone to prison for it, and carried it to the throne — that petition, of all petitions, came before that emperor, of all emperors.',

  /* ── §十 终判与残页 ─────────────────────────────────── */
  t049: 'The emperor ordered the case sent to the <span class="term" data-annot="annot-duchayuan">Censorate</span>, and the Censorate referred it downward. For the first time, the case files that had been seized, hidden, swapped and altered over eight years lay open together on one table.',
  t168: '<b>The Censorate (duchayuan).</b> The empire’s highest organ of surveillance, charged with disciplining officials and trying cases of official misconduct. The Regional Inspectors sent to the provinces came out of it.',   // [鹿诺初译]
  t050: 'The final judgment came down. It found: Luo Qiuyin was a man of the Tang, buried at Yanggan; this was established, and the grave was not a forgery. As to the absence of bones — after several hundred years remains return to earth, which is only to be expected, and it cannot be argued from this that the grave is false. The grave was awarded to the Luo family and was to be repaired as before; the epitaph stone was to be reburied in front of it; and the descendants of the Luos were to sweep and sacrifice there in perpetuity.',
  t084: '<p>A six-hundred-year-old grave is genuine: for that one sentence from the government, the Luo family had spent eight years and four thousand taels of silver, had watched the tomb levelled twice, and had thrown in a term of imprisonment besides. And when you read down to the sentencing, there is something unexpected: Luo Xian, ninety strokes; Fachun, seventy. The family that won the case was beaten harder than the side that lost it.</p>',
  t051: 'This final judgment, which accounted for the rights and wrongs of eight years one item at a time, left exactly one man without any sequel at all: Zheng Laibao. Eight years on, his death had still not been given an explanation. Perhaps the truth was that he did die of illness — that the Luos wrote up a funeral as their opponents’ homicide. That is what was false in Luo Xian’s “false statement in a memorial.” In the book he later cut himself, this page carries not one word in his own defence.',   // [据花诗英文改写]
  t052: 'The epitaph stone was reburied in front of the grave.',   // [据花诗英文改写]
  t063: 'Three years later, in 1538, Luo Xian did the last thing he would do in this lawsuit: he had the eight years of case files cut into a book.',   // [据花诗英文改写]
  t135: '<span class="who">A KINSMAN</span>We have the files of all eight years. Why cut only this one volume? Cut them all.',   // [鹿诺初译]
  t136: '<span class="who">LUO XIAN</span>The files are too long; they say the same things over and over. A reader will fall asleep. We cut only this — the final judgment, where it all comes together.',   // [鹿诺初译]
  t137: '<span class="who">A KINSMAN</span>And what Fachun said against us? Print that too, and send it out into the world? How will that look?',   // [鹿诺初译]
  t138: '<span class="who">LUO XIAN</span>This book is to be producible in court. With only our own words in it, one sentence — “you made it up” — and several hundred copies are cut for nothing.',   // [鹿诺初译]
  t064: 'Why cut it himself? Because in eight years he had seen it with his own eyes: a government file could be drawn out by a man using someone else’s name, could have a volume removed from it, could have its characters altered at one tael of silver a place. He no longer trusted anybody.',   // [据花诗英文改写]
  t172: '“The files are prolix, the wording repetitive and the sense reiterated, so that readers weary of them… Distributed within the lineage, one copy kept in each household… to shut off any covetous designs.”',   // [鹿诺初译]
  t173: '“Relying on their faction and their patronage they schemed to have it all obliterated; but Heaven’s principle answered clear and manifest… Seven memorials laid before the throne, and from beginning to end eight years, before it was brought to a conclusion.”',   // [鹿诺初译]
  t065: 'Several hundred copies were printed and given out to the branches of the clan, one copy kept in each household.',   // [鹿诺初译]
  t053: 'In the same year, in Beijing, the emperor obtained at last the <span class="term" data-annot="annot-miaohao">temple name</span> he wanted for his natural father. An emperor and a Huizhou lineage head, in the same year, each brought to an end his war over the standing of an ancestor.',   // [据花诗英文改写]
  t169: '<b>Temple name (miaohao).</b> The title under which a deceased emperor is worshipped in the imperial ancestral temple — the “Zu” and “Zong” names. To confer one posthumously on a man who had never reigned was to raise him into the ranks of emperors; within the ritual order of the dynasty, this was a matter of the very first magnitude.',   // [鹿诺初译]
  t054: 'Thirty years later, when the government recompiled the <i>Huizhou Prefectural Gazetteer</i>, the account of Yanggan Monastery’s origins under its entry was changed to the version the Luo family had argued for in court.',
  t055: 'Luo Xian’s book is kept today in Beijing, in the library of the Institute of History of the Chinese Academy of Social Sciences. One case, one volume, twenty-six leaves, something over ten thousand characters. The eight years you have just read — every exchange in the courtroom, every bribe at the banquet table — come almost entirely out of this book.',
  t085: '<p>Everything the government’s files suffered — stolen, swapped, altered — this book was proof against. And yet, in coming down to us, it too has lost a leaf. One of the twenty-six is missing, and it happens to break off in the middle of a sentence. At the foot of the preceding page stand four characters—</p>',

  /* ── 尾声 · 议论层（取自花诗英文正文 v5 结尾议论） ───── */
  t068: '<p>Reading this far, you may have been carrying one question the whole way: it is a grave. Did it really warrant eight years of mutual destruction?</p>',
  t069: '<p>Nobody inside this case thought anyone was overreacting. For that grave, the monks were willing to lay gold and silver on a banquet table to buy testimony; the Luos were willing to stake generations of savings; and in Beijing, in those very years, the emperor fought his entire government for more than a decade over his own father’s title — and on one day had more than a hundred protesting officials beaten with rods in the palace courtyard, more than ten of them to death. From the emperor down to the farmers, the whole age was paying in blood for the names of its ancestors — because in that world, an ancestor’s name was the most practical thing a family owned. It determined why several hundred people counted as one family; it determined who owned the clan’s land; it determined whether yours was a family of standing in the district, or a family anyone could reach into at will. Understand that, and Luo Xian’s eight years stop looking like obsession. He had no way back.</p>',
  t070: '<p>Now consider the eight years themselves. The easiest reading is this: Luo Xian had bad luck — he ran into a nest of bad men. But take these people out and look at them one at a time, and almost none of them thought of themselves as doing evil. The magistrate wanted cases closed — his superiors graded him on the size of his backlog, not on the number of his miscarriages. The clerks and runners wanted to eat — they drew almost no pay, a few taels of “meal silver” a year, and lived off the cases that passed through their hands; a tael for altering a character was a crime under the statutes, and in their line of work it was simply what such work went for. The grand coordinator sending complaints back down was office routine. The two magistrates writing five deaths off as illness was the quickest way to file a case closed. The Chizhou judge dared to take money and use the press because he knew this case would pass through his court exactly once, and nothing that happened in it would ever be traced back to him. Every one of them at his own post, doing things by the rules or by the going rate — and the sum of it all is the eight years that Luo Xian got.</p>',
  t071: '<p>Then where does the fault lie? In what that government was actually for. A Ming county magistrate ran the taxes, the policing, the schools and the lawsuits of an entire county; judging cases was one duty among many, and the throne graded him on whether the taxes came in full, whether his district stayed quiet, whether his docket was clear. Which is to say: the yamen’s task was never to do the common people justice. It was to keep the realm stable. Case closed, parties silent, district calm — the task was done. Whether black and white had actually been told apart, and who had been wronged along the way — the assessment form had no line for that.</p> <p>The bond of settlement set this logic down in writing: what marked a case as finished was not that the truth had been found, but that both parties had signed a pledge to stop suing. That is why a ruling could split the difference — grave rights to one side, property to the other; that is why five deaths could become “illness.” Where stability was wanted, justice could always be spent — and the yamen spent it with a perfectly clear conscience, because keeping things stable was precisely the duty the throne had given it.</p>',
  t072: '<p>But justice traded away for stability buys no stability. Both litigants soon read the court’s mind, and what it told them was this: no one is going to find the truth for you — stop first, and the matter is settled on your opponent’s terms; and the other way around, make a big enough disturbance, and the government, wanting quiet, will renegotiate anything. So neither side dared stop, and both kept raising the stakes: Luo Xian appealing upward, Fachun inventing a murder; you buy witnesses, I steal files. Eight years of a lawsuit that grew and grew — and it will not do to blame two uncommonly stubborn families. Under these rules, refusing to quit was the only move that did not lose.</p> <p>Fachun saw this more clearly than anyone: his three hundred taels were a wager on the court’s appetite for quiet. And Luo Xian, in the end, saw it too — that is why, when he printed his book, he set his enemy’s testimony in it verbatim and said the book must be fit to present in court someday. Even the man who had won could not believe the lawsuit was truly over. Justice had been spent in the name of stability, and stability was not obtained either: in those eight years, this corner of Huizhou never once knew quiet.</p>',
  t073: '<p>What settled the truth in the end, then? The honest answer is: luck. Every measure of justice the local courts gave Luo Xian in eight years was overturned. The one that could not be overturned came because a Transmission Commissioner was willing to read a village grave case aloud at morning court — and because the man on the throne happened to be, of every emperor in the dynasty’s history, the one who took the words “an ancestor’s name” most personally to heart. Filed twenty years earlier or twenty years later, this petition almost certainly ends another way. Luo Xian won because he lasted to that day — and because on that day, it happened that someone was willing to take his case up.</p>',
  t074: '<p>Look back, now, at what Luo Xian actually won. The grave was saved; the name was restored. The price: eight years; the savings of generations; Zheng Laibao’s life — and five deaths sealed under two characters, never to be spoken of again. The final judgment affirmed that the grave was real, and still sentenced him to ninety strokes for “false statement in a memorial” — twenty more than Fachun, the man who had bought testimony and invented dead men. The winner of the lawsuit was beaten harder than the loser; of all the men who had wronged him, not one was pursued to the end. And to the very last, that government never once said to him: you were right.</p>',
  t107: '<p>Seen from here, the book was more than a winner’s memorial. In eight years he had watched government files walk whole out of government archives; watched sworn testimony reversed under the witnesses’ own names at a tael per character; watched five human lives become “died of illness” in the text of a judgment. And he knew that the official histories were not his to write — in the gazetteers as they stood, the origins of Yanggan were told the monks’ way. All the ink of the empire belonged to the government, and he no longer trusted one word from that pen.</p> <p>So this countryman did what no court historian would ever have done for him: his grievances, his lawsuit, the justice he had clawed back, and his enemies’ own confessions — carved, word by word, onto woodblocks; printed by the hundred; dispersed into the family chests of his clan. The dynasty could rewrite its files, and the historians could rewrite their gazetteers; they could not rewrite several hundred identical books lying in several hundred household chests. It was one small man’s final claim against the official pen: what you refuse to write, I will write myself; what you have written falsely, I hold the proof against you. Four hundred years have passed. The courtrooms have fallen, the archives have scattered, the gazetteers have been revised and revised again — and the book is still here. The justice a Ming villager carved for himself has outlived the emperor’s edicts, the inspectors’ seals, and every archive the Huizhou yamen ever kept.</p>',

  /* ── 尾声 · 拾遗层（取自花诗尾声文案 v5 English 十段） ─ */
  t075: '<p>Turn now to the government’s side. Two pieces of writing came of this lawsuit there. One is the final judgment: the grave to the Luo family, ninety strokes for Luo Xian, seventy for Fachun. The other is the Huizhou gazetteer, recompiled thirty years later, where the account of Yanggan Monastery was changed to the version the Luo family had argued in court, setting down the year the monastery was founded and who held its land.</p>',
  t076: '<p>What the judgment and the gazetteer do not record is what you have just read: that he cleared a winter’s worth of rubble off his ancestor’s grave, waited for the monastery to explain itself, and was told to move the grave elsewhere; that the first time he stood in the county court, Fachun took his evidence apart point by point until he had nothing left to say; that three years later, in a court of the same kind, he recited every bribe his opponents had paid, the sum, the day, and the name of each man who took it, and turned their witnesses into evidence against them; that in Chizhou the session was held after dark with the streets under curfew and no onlooker outside, and the court called no neighbours, sent for no earlier file, heard no defence of his, and went straight to the ankle press; and that his nephew Luo Xing knew he would be imprisoned on reaching the capital and carried the petition there anyway.</p>',
  t077: '<p>The judgment and the gazetteer are not inaccurate, and no official’s bribe-taking produced this. A gazetteer sets down how much land a prefecture holds, how many households, which monastery was founded in what year and who holds its property; a judgment sets down what a man did and how much he is to be punished. Neither document has anywhere in it for what kind of man Luo Xian was. Had the Shexian magistrate taken no money, had the Chizhou judge left the ankle press alone, had the gazetteer’s compilers written the Luo version from the start, neither the judgment nor the gazetteer would still say why he refused to yield. The compilers and the judges did not leave it out. Neither kind of document has a column for it.</p>',
  t078: '<p>Each of the two documents had its own use. A judgment went up for review by higher authority, and it was enough for it to state the offence and the sentence; a gazetteer was read by the court and by later officials, and it was enough for it to state a foundation history and the ownership of land. A step above that, to run a county or a prefecture the authorities had to know how many acres of land there were, how many people in a household, how much tax came in, what sentence each man received, and those figures had to be checkable and comparable with last year’s. Why Luo Xian would not yield was of no use to either document, and so neither gave it a place. This was not peculiar to the Yanggan case: documents compiled by government offices exist for the work of those offices, and what the work has no use for is not written down. Which side won made no difference to that. When the gazetteer adopted the Luo version thirty years on, it looked like a victory, but what the revised gazetteer sets down is the same few items as before — the year of founding, the ownership of the land — and why he would not yield is no more written there after the revision than it was before.</p>',
  t101: 'What one remembers of these eight years, though, is precisely what the judgment and the gazetteer do not record: that he waited for an explanation and was told to move his ancestor out; that he staked generations of his clan’s savings; that he watched the grave levelled twice. Those things were of no use to the empire, and they were what those eight years of his life actually consisted of. Of that life the state’s writing preserves two lines of a judgment; everything else he did in those eight years, so far as government paper goes, may as well not have happened.',
  t079: '<p>The grave had already been restored to him, and he cut the book anyway. His kinsmen urged him to print the whole file; he refused, saying it ran too long and a reader would fall asleep over it, and printed only the volume of the final judgment. He copied the testimony of Fachun’s side without altering a word, and noted that the book had to be fit one day for presentation in court: what he wanted was a record his opponents could not fault. Of that night in Chizhou he set down four characters in the book, <i>pressed and beaten, against the law</i>.</p>',   // [据花诗英文改写] 08-08 与t152/t171同字（花诗审校必改2）
  t108: '<p>Four hundred and seventy years later the Turkish novelist Orhan Pamuk, in Istanbul, did something of the same kind. He held that in the great museums built for nations one cannot see any particular person, and he wrote eleven propositions on the subject. One holds that the measure of a museum’s success should not be its ability to represent a state, a nation or company, or a particular history, but its capacity “to reveal the humanity of individuals.” Another puts it more directly: the aim of museums, he writes, “must not be to represent the state, but to re-create the world of single human beings” — and he specifies whom he means: “the same human beings who have labored under ruthless oppression for hundreds of years.” He observes, besides, that the transition from palaces to national museums and the transition from epics to novels ran parallel to each other.</p>',   // [据花诗英文改写] 08-08 帕慕克两句加引号；引号内用2012 Abrams版原书美式拼写"labored"，不随全表改"laboured"（花诗审校必改6，她自认的错）
  t080: '<p>Having written the eleven propositions, he built a museum of his own. A nineteenth-century wooden house in Çukurcuma, in Istanbul’s Beyoğlu district; a thousand-odd objects, all of them presented as things used by Füsun, a woman out of his own novel; one glass case holding the 4,213 cigarette stubs she had smoked. Füsun is a character in a novel; the 4,213 stubs are physical objects, on display in the house. The museum tells no part of Turkey’s history, only the years in which one person loved another.</p>',
  t086: '<p>What the two men did was not the same: one cut an eight-year lawsuit into printing blocks and put a copy in each of several hundred households; the other arranged the everyday belongings of an invented woman in a wooden house. They have one thing in common: no particular person can be seen in the documents government offices compile, or in the museums that states build.</p>',

  /* ── 六份供词那一格的窄屏说明行（图上叠字在手机上收起） ─────── */
  t188: 'Six depositions, word for word the same: <i>Luo Xian bribed us to testify — fifty taels of silver.</i>',   // [鹿诺初译]
  t189: 'Six depositions, word for word the same: <i>Luo Xian bribed us to testify — fifty taels of silver.</i>',   // [鹿诺初译]

  /* 其余条目（叙述 52、讲解 21、台词、注释 15、嵌图字、原文块、侧边文字）
     与 GLOSS 素材标注表，分批补入。 */
};

/* 素材上的中文：不改素材，英文态在该格下补一行小字说明写的是什么。
   （下一批补齐；键为 data-gloss 的编号。） 08-08 删掉此处原有的重复空赋值
   （window.EN_GLOSS 曾被赋值两次，第二次悄悄覆盖第一次；花诗审校代码一处已改） */

/* ══ 素材上的中文：英文标注表 ══════════════════════════════════════════
   〔用户裁定·2026-08-07·当面会话·"不必动素材，对素材上的中文加标注翻译"〕
   画面里的文书是明代的文书，字不动；英文态在那一格下面补一行小字，说明它写的是什么。
   全部 13 条都是我写的（花诗的英文稿里没有对应文字），所以整表按 [鹿诺初译] 送她审校。
   （g05、g11 两条 2026-08-07 已撤，原 15 条降为 13 条，见下方说明。）
   人名、官名、"painian"这类词沿用她英文正文里已定的译法，没有另起炉灶。
   ────────────────────────────────────────────────────────────────── */
window.EN_GLOSS = {

  /* g05 与 g11 已撤（2026-08-07）：六份赃证那两格里另有一个说明块（`gongci-note`，
     编号 t188／t189），中英文都有、已经把画面上写的字说清楚了；再挂一条标注，英文态
     下同一格会把同一件事说两遍（实测两句并排显示）。撤掉的是我加的这一条，说明块不动。
     编号保持不连续，不重排——重排会让已经审过的条目错位。 */

  g01: 'The county summons. In the large characters, the charge: <i>forging an ancestral grave</i>. Beside it: Luo Xian of Chengkan — fourth month of 1528 — to appear at the county court for hearing.',

  g02: 'The monastery’s new complaint, filed as a homicide. <i>Concerning a killing.</i> The Luo family schemed after temple property and led a mob into the monastery; they beat to death the monks of this house, Nengni and Foyuan.',

  g03: 'The five annual-service men (<i>painian</i>) who had taken the monastery’s silver, named one after another: Hu Tongjin, Li Tinggang, Fan Qionglong, Wang Lin, Li Wenhao.',   // 08-08 与正文"annual-service men"统一，删"tax captains"（与t033立论相抵）（花诗审校必改5）

  g04: 'The contents of the case file: <i>the original Shexian hearing, one fascicle; the Ningguo hearing, one fascicle; the bond of settlement.</i> Against the last, an empty column.',

  g06: 'Four depositions, each turned around by one character. <i>There has always been an ancient grave here</i> — the character for “is” scraped out with a knife, and “is not” cut into the space it left.',

  g07: 'The Huizhou register of monks: nine ruled columns, eight names entered — Fachun, Foxi, Nengni, Zhideng, Foyuan, Faming, Nengzheng, Fohai. Under Nengni, and under Foyuan, stands a single word: <i>deceased</i>.',

  g08: 'The final judgment, in four lines: <i>Luo Qiuyin was a man of the Tang, and his burial at Yanggan is verified. After so many years his remains have turned to earth, which is in the nature of things. The grave is awarded to the Luo family, to be repaired as before. The epitaph stone is to be reburied before the grave, and his descendants to sweep and sacrifice hereafter.</i>',

  g09: 'The prefectural gazetteer entry: <i>Yanggan Monastery, in Chengkan township. The sixth year of Baoyou, under the Song. Built by the Luo clan to keep watch over a grave.</i>',

  g10: 'The earlier Huizhou judgment: <i>Having examined the statements of the accused, and the stele and the old gazetteers — this monastery was built because of the grave, and the grave has been ruined because of the monastery. In reason: to raze the monastery and keep the grave would be allowable; to destroy the grave and keep the monastery is not.</i> Where the page is torn through, four characters survive: <i>how could the Luo family—</i>',

  g12: 'The final judgment again — the four lines that closed the case.',

  g13: 'The gazetteer entry again: <i>Yanggan Monastery, in Chengkan township. The sixth year of Baoyou, under the Song. Built by the Luo clan to keep watch over a grave.</i>',

  g14: 'The land register of 1391. Parcel after parcel of Luo land, and against them all the same four characters entered in the margin: <i>all managed by the monastery</i>.',

  g15: 'Luo Xian’s complaint, in three moves: <i>first, the unlawful acts of the monks; then, the history of the grave; last, the county magistrate’s taking of bribes.</i>'
};
